name: Test coverage (Ubuntu)

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-all:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: true

            - name: Install dependencies
              run: sources/build/scripts/setup-ubuntu.sh

            - name: Run Tests
              run: |
                  TOOLCHAIN=llvm ./stratus.sh --coverage test
                  llvm-profdata-13 merge -sparse `find . -name "*.profraw"` -o coverage.profdata
                  llvm-cov-13 show ./bin/devel/x86_64-host-llvm/test -instr-profile=coverage.profdata -format=text > coverage.txt

            - name: Upload test coverage
              uses: codecov/codecov-action@v2
              with:
                  fail_ci_if_error: true
