name: Build and Test (Darwin)

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-all:
        runs-on: macos-11

        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: true

            - name: Install dependencies
              run: sources/build/scripts/setup-darwin.sh

            - name: Build All
              run: |
                  sources/build/scripts/env-darwin.sh make all

            - name: Run Tests
              run: |
                  sources/build/scripts/env-darwin.sh ./brutal.sh test
